// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/res_ActCondStageTask.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PbProtocol {

  /// <summary>Holder for reflection information generated from Proto/res_ActCondStageTask.proto</summary>
  public static partial class ResActCondStageTaskReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/res_ActCondStageTask.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResActCondStageTaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBQcm90by9yZXNfQWN0Q29uZFN0YWdlVGFzay5wcm90bxILcGJfUHJvdG9j",
            "b2wiPAoXcGJBY3RDb25kU3RhZ2VUYXNrQXdhcmQSDwoFUmVzSUQYxKUBIAEo",
            "BRIQCgZSZXNOdW0YhNEBIAEoBSL4AQoScGJBY3RDb25kU3RhZ2VUYXNrEhAK",
            "BlRhc2tJRBj2rgEgASgFEhYKDE1heERvbmVDb3VudBiVogEgASgFEhMKCVJl",
            "c2V0VHlwZRjkrgEgASgFEhIKCFRhc2tOYW1lGKrnASABKAkSEgoIVGFza0Rl",
            "c2MYqL8BIAEoCRIbChFGaW5pc2hDb25kaXRpb25JRBiqrAEgASgFEhcKDVRh",
            "cmdldFByb2Nlc3MYj+oBIAEoBRJFChVBY3RDb25kU3RhZ2VUYXNrQXdhcmQY",
            "8eMBIAMoCzIkLnBiX1Byb3RvY29sLnBiQWN0Q29uZFN0YWdlVGFza0F3YXJk",
            "Ko4BCi5QQl9NQUNST19NQVhfQUNUQ09ORFNUQUdFVEFTS19UQVNLTkFNRV9T",
            "VFJfTEVOEi4KKlBCX01BWF9BQ1RDT05EU1RBR0VUQVNLX1RBU0tOQU1FX1NU",
            "Ul9MRU5fMBAAEiwKKFBCX01BWF9BQ1RDT05EU1RBR0VUQVNLX1RBU0tOQU1F",
            "X1NUUl9MRU4QICqOAQouUEJfTUFDUk9fTUFYX0FDVENPTkRTVEFHRVRBU0tf",
            "VEFTS0RFU0NfU1RSX0xFThIuCipQQl9NQVhfQUNUQ09ORFNUQUdFVEFTS19U",
            "QVNLREVTQ19TVFJfTEVOXzAQABIsCihQQl9NQVhfQUNUQ09ORFNUQUdFVEFT",
            "S19UQVNLREVTQ19TVFJfTEVOECAqtQEKO1BCX01BQ1JPX01BWF9BQ1RDT05E",
            "U1RBR0VUQVNLX0FDVENPTkRTVEFHRVRBU0tBV0FSRF9DRkdfTlVNEjsKN1BC",
            "X01BWF9BQ1RDT05EU1RBR0VUQVNLX0FDVENPTkRTVEFHRVRBU0tBV0FSRF9D",
            "RkdfTlVNXzAQABI5CjVQQl9NQVhfQUNUQ09ORFNUQUdFVEFTS19BQ1RDT05E",
            "U1RBR0VUQVNLQVdBUkRfQ0ZHX05VTRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PbProtocol.PB_MACRO_MAX_ACTCONDSTAGETASK_TASKNAME_STR_LEN), typeof(global::PbProtocol.PB_MACRO_MAX_ACTCONDSTAGETASK_TASKDESC_STR_LEN), typeof(global::PbProtocol.PB_MACRO_MAX_ACTCONDSTAGETASK_ACTCONDSTAGETASKAWARD_CFG_NUM), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PbProtocol.pbActCondStageTaskAward), global::PbProtocol.pbActCondStageTaskAward.Parser, new[]{ "ResID", "ResNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PbProtocol.pbActCondStageTask), global::PbProtocol.pbActCondStageTask.Parser, new[]{ "TaskID", "MaxDoneCount", "ResetType", "TaskName", "TaskDesc", "FinishConditionID", "TargetProcess", "ActCondStageTaskAward" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PB_MACRO_MAX_ACTCONDSTAGETASK_TASKNAME_STR_LEN {
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_TASKNAME_STR_LEN_0")] PbMaxActcondstagetaskTasknameStrLen0 = 0,
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_TASKNAME_STR_LEN")] PbMaxActcondstagetaskTasknameStrLen = 32,
  }

  public enum PB_MACRO_MAX_ACTCONDSTAGETASK_TASKDESC_STR_LEN {
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_TASKDESC_STR_LEN_0")] PbMaxActcondstagetaskTaskdescStrLen0 = 0,
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_TASKDESC_STR_LEN")] PbMaxActcondstagetaskTaskdescStrLen = 32,
  }

  public enum PB_MACRO_MAX_ACTCONDSTAGETASK_ACTCONDSTAGETASKAWARD_CFG_NUM {
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_ACTCONDSTAGETASKAWARD_CFG_NUM_0")] PbMaxActcondstagetaskActcondstagetaskawardCfgNum0 = 0,
    [pbr::OriginalName("PB_MAX_ACTCONDSTAGETASK_ACTCONDSTAGETASKAWARD_CFG_NUM")] PbMaxActcondstagetaskActcondstagetaskawardCfgNum = 3,
  }

  #endregion

  #region Messages
  public sealed partial class pbActCondStageTaskAward : pb::IMessage<pbActCondStageTaskAward> {
    private static readonly pb::MessageParser<pbActCondStageTaskAward> _parser = new pb::MessageParser<pbActCondStageTaskAward>(() => new pbActCondStageTaskAward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pbActCondStageTaskAward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PbProtocol.ResActCondStageTaskReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTaskAward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTaskAward(pbActCondStageTaskAward other) : this() {
      resID_ = other.resID_;
      resNum_ = other.resNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTaskAward Clone() {
      return new pbActCondStageTaskAward(this);
    }

    /// <summary>Field number for the "ResID" field.</summary>
    public const int ResIDFieldNumber = 21188;
    private int resID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResID {
      get { return resID_; }
      set {
        resID_ = value;
      }
    }

    /// <summary>Field number for the "ResNum" field.</summary>
    public const int ResNumFieldNumber = 26756;
    private int resNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResNum {
      get { return resNum_; }
      set {
        resNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pbActCondStageTaskAward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pbActCondStageTaskAward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResID != other.ResID) return false;
      if (ResNum != other.ResNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResID != 0) hash ^= ResID.GetHashCode();
      if (ResNum != 0) hash ^= ResNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResID != 0) {
        output.WriteRawTag(160, 172, 10);
        output.WriteInt32(ResID);
      }
      if (ResNum != 0) {
        output.WriteRawTag(160, 136, 13);
        output.WriteInt32(ResNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResID != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(ResID);
      }
      if (ResNum != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(ResNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pbActCondStageTaskAward other) {
      if (other == null) {
        return;
      }
      if (other.ResID != 0) {
        ResID = other.ResID;
      }
      if (other.ResNum != 0) {
        ResNum = other.ResNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 169504: {
            ResID = input.ReadInt32();
            break;
          }
          case 214048: {
            ResNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class pbActCondStageTask : pb::IMessage<pbActCondStageTask> {
    private static readonly pb::MessageParser<pbActCondStageTask> _parser = new pb::MessageParser<pbActCondStageTask>(() => new pbActCondStageTask());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pbActCondStageTask> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PbProtocol.ResActCondStageTaskReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTask() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTask(pbActCondStageTask other) : this() {
      taskID_ = other.taskID_;
      maxDoneCount_ = other.maxDoneCount_;
      resetType_ = other.resetType_;
      taskName_ = other.taskName_;
      taskDesc_ = other.taskDesc_;
      finishConditionID_ = other.finishConditionID_;
      targetProcess_ = other.targetProcess_;
      actCondStageTaskAward_ = other.actCondStageTaskAward_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbActCondStageTask Clone() {
      return new pbActCondStageTask(this);
    }

    /// <summary>Field number for the "TaskID" field.</summary>
    public const int TaskIDFieldNumber = 22390;
    private int taskID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TaskID {
      get { return taskID_; }
      set {
        taskID_ = value;
      }
    }

    /// <summary>Field number for the "MaxDoneCount" field.</summary>
    public const int MaxDoneCountFieldNumber = 20757;
    private int maxDoneCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxDoneCount {
      get { return maxDoneCount_; }
      set {
        maxDoneCount_ = value;
      }
    }

    /// <summary>Field number for the "ResetType" field.</summary>
    public const int ResetTypeFieldNumber = 22372;
    private int resetType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResetType {
      get { return resetType_; }
      set {
        resetType_ = value;
      }
    }

    /// <summary>Field number for the "TaskName" field.</summary>
    public const int TaskNameFieldNumber = 29610;
    private string taskName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskName {
      get { return taskName_; }
      set {
        taskName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TaskDesc" field.</summary>
    public const int TaskDescFieldNumber = 24488;
    private string taskDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskDesc {
      get { return taskDesc_; }
      set {
        taskDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FinishConditionID" field.</summary>
    public const int FinishConditionIDFieldNumber = 22058;
    private int finishConditionID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FinishConditionID {
      get { return finishConditionID_; }
      set {
        finishConditionID_ = value;
      }
    }

    /// <summary>Field number for the "TargetProcess" field.</summary>
    public const int TargetProcessFieldNumber = 29967;
    private int targetProcess_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetProcess {
      get { return targetProcess_; }
      set {
        targetProcess_ = value;
      }
    }

    /// <summary>Field number for the "ActCondStageTaskAward" field.</summary>
    public const int ActCondStageTaskAwardFieldNumber = 29169;
    private static readonly pb::FieldCodec<global::PbProtocol.pbActCondStageTaskAward> _repeated_actCondStageTaskAward_codec
        = pb::FieldCodec.ForMessage(233354, global::PbProtocol.pbActCondStageTaskAward.Parser);
    private readonly pbc::RepeatedField<global::PbProtocol.pbActCondStageTaskAward> actCondStageTaskAward_ = new pbc::RepeatedField<global::PbProtocol.pbActCondStageTaskAward>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::PbProtocol.pbActCondStageTaskAward> ActCondStageTaskAward {
      get { return actCondStageTaskAward_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pbActCondStageTask);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pbActCondStageTask other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskID != other.TaskID) return false;
      if (MaxDoneCount != other.MaxDoneCount) return false;
      if (ResetType != other.ResetType) return false;
      if (TaskName != other.TaskName) return false;
      if (TaskDesc != other.TaskDesc) return false;
      if (FinishConditionID != other.FinishConditionID) return false;
      if (TargetProcess != other.TargetProcess) return false;
      if(!actCondStageTaskAward_.Equals(other.actCondStageTaskAward_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskID != 0) hash ^= TaskID.GetHashCode();
      if (MaxDoneCount != 0) hash ^= MaxDoneCount.GetHashCode();
      if (ResetType != 0) hash ^= ResetType.GetHashCode();
      if (TaskName.Length != 0) hash ^= TaskName.GetHashCode();
      if (TaskDesc.Length != 0) hash ^= TaskDesc.GetHashCode();
      if (FinishConditionID != 0) hash ^= FinishConditionID.GetHashCode();
      if (TargetProcess != 0) hash ^= TargetProcess.GetHashCode();
      hash ^= actCondStageTaskAward_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MaxDoneCount != 0) {
        output.WriteRawTag(168, 145, 10);
        output.WriteInt32(MaxDoneCount);
      }
      if (FinishConditionID != 0) {
        output.WriteRawTag(208, 226, 10);
        output.WriteInt32(FinishConditionID);
      }
      if (ResetType != 0) {
        output.WriteRawTag(160, 246, 10);
        output.WriteInt32(ResetType);
      }
      if (TaskID != 0) {
        output.WriteRawTag(176, 247, 10);
        output.WriteInt32(TaskID);
      }
      if (TaskDesc.Length != 0) {
        output.WriteRawTag(194, 250, 11);
        output.WriteString(TaskDesc);
      }
      actCondStageTaskAward_.WriteTo(output, _repeated_actCondStageTaskAward_codec);
      if (TaskName.Length != 0) {
        output.WriteRawTag(210, 186, 14);
        output.WriteString(TaskName);
      }
      if (TargetProcess != 0) {
        output.WriteRawTag(248, 208, 14);
        output.WriteInt32(TargetProcess);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TaskID != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(TaskID);
      }
      if (MaxDoneCount != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(MaxDoneCount);
      }
      if (ResetType != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(ResetType);
      }
      if (TaskName.Length != 0) {
        size += 3 + pb::CodedOutputStream.ComputeStringSize(TaskName);
      }
      if (TaskDesc.Length != 0) {
        size += 3 + pb::CodedOutputStream.ComputeStringSize(TaskDesc);
      }
      if (FinishConditionID != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(FinishConditionID);
      }
      if (TargetProcess != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(TargetProcess);
      }
      size += actCondStageTaskAward_.CalculateSize(_repeated_actCondStageTaskAward_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pbActCondStageTask other) {
      if (other == null) {
        return;
      }
      if (other.TaskID != 0) {
        TaskID = other.TaskID;
      }
      if (other.MaxDoneCount != 0) {
        MaxDoneCount = other.MaxDoneCount;
      }
      if (other.ResetType != 0) {
        ResetType = other.ResetType;
      }
      if (other.TaskName.Length != 0) {
        TaskName = other.TaskName;
      }
      if (other.TaskDesc.Length != 0) {
        TaskDesc = other.TaskDesc;
      }
      if (other.FinishConditionID != 0) {
        FinishConditionID = other.FinishConditionID;
      }
      if (other.TargetProcess != 0) {
        TargetProcess = other.TargetProcess;
      }
      actCondStageTaskAward_.Add(other.actCondStageTaskAward_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 166056: {
            MaxDoneCount = input.ReadInt32();
            break;
          }
          case 176464: {
            FinishConditionID = input.ReadInt32();
            break;
          }
          case 178976: {
            ResetType = input.ReadInt32();
            break;
          }
          case 179120: {
            TaskID = input.ReadInt32();
            break;
          }
          case 195906: {
            TaskDesc = input.ReadString();
            break;
          }
          case 233354: {
            actCondStageTaskAward_.AddEntriesFrom(input, _repeated_actCondStageTaskAward_codec);
            break;
          }
          case 236882: {
            TaskName = input.ReadString();
            break;
          }
          case 239736: {
            TargetProcess = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
