// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/res_RuleDesc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PbProtocol {

  /// <summary>Holder for reflection information generated from Proto/res_RuleDesc.proto</summary>
  public static partial class ResRuleDescReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/res_RuleDesc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResRuleDescReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQcm90by9yZXNfUnVsZURlc2MucHJvdG8SC3BiX1Byb3RvY29sIjsKCnBi",
            "UnVsZURlc2MSDAoCSUQYg+QBIAEoBRIPCgVUaXRsZRiXsAEgASgJEg4KBERl",
            "c2MYj94BIAEoCSptCiNQQl9NQUNST19NQVhfUlVMRURFU0NfVElUTEVfU1RS",
            "X0xFThIjCh9QQl9NQVhfUlVMRURFU0NfVElUTEVfU1RSX0xFTl8wEAASIQod",
            "UEJfTUFYX1JVTEVERVNDX1RJVExFX1NUUl9MRU4QICprCiJQQl9NQUNST19N",
            "QVhfUlVMRURFU0NfREVTQ19TVFJfTEVOEiIKHlBCX01BWF9SVUxFREVTQ19E",
            "RVNDX1NUUl9MRU5fMBAAEiEKHFBCX01BWF9SVUxFREVTQ19ERVNDX1NUUl9M",
            "RU4QgAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PbProtocol.PB_MACRO_MAX_RULEDESC_TITLE_STR_LEN), typeof(global::PbProtocol.PB_MACRO_MAX_RULEDESC_DESC_STR_LEN), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PbProtocol.pbRuleDesc), global::PbProtocol.pbRuleDesc.Parser, new[]{ "ID", "Title", "Desc" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PB_MACRO_MAX_RULEDESC_TITLE_STR_LEN {
    [pbr::OriginalName("PB_MAX_RULEDESC_TITLE_STR_LEN_0")] PbMaxRuledescTitleStrLen0 = 0,
    [pbr::OriginalName("PB_MAX_RULEDESC_TITLE_STR_LEN")] PbMaxRuledescTitleStrLen = 32,
  }

  public enum PB_MACRO_MAX_RULEDESC_DESC_STR_LEN {
    [pbr::OriginalName("PB_MAX_RULEDESC_DESC_STR_LEN_0")] PbMaxRuledescDescStrLen0 = 0,
    [pbr::OriginalName("PB_MAX_RULEDESC_DESC_STR_LEN")] PbMaxRuledescDescStrLen = 256,
  }

  #endregion

  #region Messages
  public sealed partial class pbRuleDesc : pb::IMessage<pbRuleDesc> {
    private static readonly pb::MessageParser<pbRuleDesc> _parser = new pb::MessageParser<pbRuleDesc>(() => new pbRuleDesc());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<pbRuleDesc> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PbProtocol.ResRuleDescReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbRuleDesc() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbRuleDesc(pbRuleDesc other) : this() {
      iD_ = other.iD_;
      title_ = other.title_;
      desc_ = other.desc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbRuleDesc Clone() {
      return new pbRuleDesc(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 29187;
    private int iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 22551;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 28431;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as pbRuleDesc);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(pbRuleDesc other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (Title != other.Title) return false;
      if (Desc != other.Desc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Title.Length != 0) {
        output.WriteRawTag(186, 129, 11);
        output.WriteString(Title);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(250, 240, 13);
        output.WriteString(Desc);
      }
      if (ID != 0) {
        output.WriteRawTag(152, 160, 14);
        output.WriteInt32(ID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 3 + pb::CodedOutputStream.ComputeInt32Size(ID);
      }
      if (Title.Length != 0) {
        size += 3 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Desc.Length != 0) {
        size += 3 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pbRuleDesc other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 180410: {
            Title = input.ReadString();
            break;
          }
          case 227450: {
            Desc = input.ReadString();
            break;
          }
          case 233496: {
            ID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
